###############################################################################
# 서비스 포트,명 등 설정 정보
# Spring Boot는 클래스 경로 아래에서 application.properties 나 .yml 파일을 자동으로 스캔하고
# 파일 구성이있는 경우 파일 구성을 로드
# Spring Boot의 다중 환경 구성 파일 이름은 application-{profile}.properties/.yml 형식을 충족
# {profile} 환경 로고에 해당
# application-local.properties/yml : 로컬 환경
# application-dev.properties/yml : 개발 환경
# application-prod.properties/yml : 운영 환경
# 다중 환경 구성 파일 활성화 속성 --- 로컬, 개발, 운영
###############################################################################
server:
  port: 8080
  error:
    whitelabel:
      enabled: true
  servlet:
    session:
      timeout: 3600
      cookie:
        name: demo-session

spring:
  application:
    name: demo
  profiles:
    default: local



###############################################################################
# DB connector 설정
###############################################################################
---
spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    password: gobizmailer
    url: jdbc:mariadb://localhost:3306/bizmailer



###############################################################################
 # jpa 설정
###############################################################################
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 10
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    open-in-view: false



###############################################################################
 # 기타 설정
###############################################################################
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  devtools:
    livereload:
      enabled: true


###############################################################################
# 로그 레벨 설정
###############################################################################
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace
